
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "login" : "jahanav",
    "password" : "password"
}



POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "login" : "jahanav",
    "password" : "password"
}